### ISSUE TITLE
Have fix for including the c libraries in cpp

### ISSUE THREAD

**Issue by codersmurf** [eclipse/tahu#125]
[tahu.zip](https://github.com/eclipse/tahu/files/6087220/tahu.zip)

All the other headers were kosher, just this one wasn't.

**Comment by jbrzozoski** [comment]
Simple enough.  I made a corresponding pull request in #126

**Comment by codersmurf** [comment]
Awesome, thx.

**Comment by jbrzozoski** [comment]
@wes-johnson this can be closed next time you're cleaning up
