### ISSUE TITLE
Project set-up

### ISSUE THREAD

**Issue by Sebeck10** [eclipse/tahu#139]
Hello,

I'm sorry to ask such a basic question. But I am on eclipse and I try to use the tahu library for a project. But I just can't add it to my project, would you have an explanation for me? 
Thanks in advance

Sebeck

**Comment by wes-johnson** [comment]
The basic process for now (until #87  is complete) is to do this:
1. Build the jar
`git clone https://github.com/eclipse/tahu.git`
`git checkout develop`
`mvn clean install`
2. Take the jar from `client_libraries/java/target/tahu-java-x.x.x-SNAPSHOT.jar` and use the process here to import it into your Eclipse project: https://stackoverflow.com/questions/3280353/how-to-import-a-jar-in-eclipse
