### ISSUE TITLE
Python death and birth bdSeq don't match

### ISSUE THREAD

**Issue by HarmGroth** [eclipse/tahu#142]
I came across that in the Python example the bdSeq in the death and birth certificate don't match.
After some research I found out that Python does not support the double minus command which is used in the birth certificate.
Instead of using "--bdSeq" it should be just "(bdSeq-1)"

https://github.com/eclipse/tahu/blob/c2f869d5c59f1ae7772e31550e8b66d18af2627c/client_libraries/python/sparkplug_b.py#L111

**Comment by jasperlg** [comment]
That is correct! Thank you!
