### ISSUE TITLE
javascript timestamp in metric

### ISSUE THREAD

**Issue by ubunturtu** [eclipse/tahu#15]
I'm using the javascript library and noticed that although in the spec it allows for a timestamp in both payload AND metric, the library only allows it in the payload but not in the metric. For example the below code will ignore the timestamp in the metric. Am I not using it correctly and if so please advise how to get it working.

{
           "timestamp" : new Date().getTime(),
            "metrics" : [
{"name":"ex","type" :"float", "timestamp" : new Date().getTime(),"value":5}
]}

**Comment by ckienle** [comment]
The metric timestamp encoding/decoding logic was missing.  I added it and now metric timestamps are working as expected.
