### ISSUE TITLE
SparkplugBPayloadDecoder should use a Long rather than a primitive long so it can be null

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/tahu#154]
From Lucas on the sparkplug-tck Slack channel on 2021-11-26:

There is a bug in the current version of eclipse Tahu which affects the EoN SessionEstablishment test:
Inside SparkplugBPayloadDecoder.java (org.eclipse.tahu.message)

```
public SparkplugBPayload buildFromByteArray(byte[] bytes) throws Exception {
    Payload protoPayload = Payload.parseFrom(bytes);
    SparkplugBPayloadBuilder builder = new SparkplugBPayloadBuilder(protoPayload.getSeq());
    if (protoPayload.hasTimestamp()) {
        builder.setTimestamp(new Date(protoPayload.getTimestamp()));
    }

    if (protoPayload.hasSeq()) {
        builder.setSeq(protoPayload.getSeq());
    }
```

the SparkplugBPayloadBuilder gets initialized with the protoPayload.getSeq() value. However it is not checked whether this value exists (protoPayload.hasSeq()) or not.
Because the sequence number is defined as primitive long this value then defaults to 0 which creates a false positive inside the SessionEstablishment test:

```
// death message must not include a sequence number
String noSeq = FAIL + " (NDEATH must not include a sequence number)";
if (sparkplugPayload.getSeq() == -1) {
   noSeq = PASS;
}
```

**Comment by mattiasbe** [comment]
@wes-johnson as per our email discussions, primitives in protobuf can't be null so this changeset is actually a bug I woudl say.
