### ISSUE TITLE
Read only Metrics

### ISSUE THREAD

**Issue by achopra6** [eclipse/tahu#17]
It would be great if metric producers can set a read-only flag for each metric. This would prevent write commands being sent to edge nodes for read only data-points as they usually have limited bandwidth available to them.

**Comment by wes-johnson** [comment]
This is a great idea.  I'd recommend seeing the new Sparkplug Working Group charter at Eclipse that will govern future changes to the spec.
https://www.eclipse.org/org/workinggroups/eclipse_sparkplug_charter.php
