### ISSUE TITLE
Java client library: no support for metric types PropertySet and PropertySetList

### ISSUE THREAD

**Issue by awonline-net** [eclipse/tahu#177]
In the Java client library PropertySet and PropertySetList data type metrics are commented out and marked as TODO in 
 [MetricDataType.java](https://github.com/eclipse/tahu/blob/master/client_libraries/java/src/main/java/org/eclipse/tahu/message/model/MetricDataType.java) The metric types are also not handled in [SparkplugBPayloadDecoder.java](https://github.com/eclipse/tahu/blob/master/client_libraries/java/src/main/java/org/eclipse/tahu/message/SparkplugBPayloadDecoder.java) and [parkplugBPayloadEncoder.java](https://github.com/eclipse/tahu/blob/master/client_libraries/java/src/main/java/org/eclipse/tahu/message/SparkplugBPayloadEncoder.java)

Are there any plans to add support for the unhandled data type metrics in the Java client library?

**Comment by wes-johnson** [comment]
The array type support has been added. However, the PropertySet and PropertySetList support is already present - but not as a MetricDataType as they are not MetricDataTypes. They are already supported as they should be as components of a Metric.

The TODO was removed: https://github.com/eclipse/tahu/pull/206
