### ISSUE TITLE
Allow TahuClient to connect using client cert/private key

### ISSUE THREAD

**Issue by jlordiales** [eclipse/tahu#331]
It looks like today it is only possible to use username+password to connect from the [TahuClient](https://github.com/eclipse/tahu/blob/master/java/lib/core/src/main/java/org/eclipse/tahu/mqtt/TahuClient.java#L144). Brokers like AWS IoT only allow connections via client cert/private keys so it would be nice to have that option as well.

All that would be needed is for the client to accept an optional `SSLSocketFactory` which could then be set in the client's `MqttConnectOptions`, similar to [this example](https://gist.github.com/jimrok/d25cb45b840f5a4ad700?permalink_comment_id=4396581#file-testmqtt-java-L51-L53). Happy to submit a PR if you think this is worth doing.

**Comment by wes-johnson** [comment]
This is definitely worth doing. Just make sure you submit the PR against the develop branch and also sign the ECA before submitting it so I can accept it.
