### ISSUE TITLE
Current proto file for Sparkplug v2.2

### ISSUE THREAD

**Issue by mikolajwalus** [eclipse/tahu#346]
Can current sparkplug_b.proto file be used to generate code for Sparkplug v2.2 version?

I tracked the changes of sparkplug_b.proto from version v2.2. They are only about comments and clarifications. Only [2790417](https://github.com/eclipse/tahu/commit/2790417bfe796704111c6aec43df4962aa4fe61c) adds DataType enum.  But id doesn't seem relevant for decoding at all (not reference directly in messages)

**Comment by wes-johnson** [comment]
Is there a reason to use v2.2 anymore?

**Comment by mikolajwalus** [comment]
Yes, many edge nodes installed on hardware still supports only 2.2. That's why I'm asking
