### ISSUE TITLE
Incorrect struct referenced in client_libraries/c/src/tahu.c

### ISSUE THREAD

**Issue by d1c0** [eclipse/tahu#36]
Line 704 reads:

`com_cirruslink_sparkplug_protobuf_Payload_PropertyValue_string_value_tag)`

but this fails to compile. Intent is probably:

`org_eclipse_tahu_protobuf_Payload_PropertyValue_string_value_tag)`

**Comment by sionhughes** [comment]
I came across the same thing. Is there a PR for this already?

**Comment by wes-johnson** [comment]
This code has been reworked thanks to @jbrzozoski. Please try out the latest code on the develop branch.
