### ISSUE TITLE
sparkplug_b_c_sharp.proto incorrect property name metric (missing the s)

### ISSUE THREAD

**Issue by danwale** [eclipse/tahu#56]
I'm implementing a C# client and have come across it complaining that there is no property called **metrics** in Payload, on inspection of the .proto file for C# it has incorrectly dropped the **s** from **metrics** and the property is being represented as **metric** instead.

When comparing the two versions of the .proto files it seems like an obvious mistake in the refactoring.

**Comment by danwale** [comment]
@wes-johnson I've submitted a pull request #58 that resolves this issue.

**Comment by wes-johnson** [comment]
Thanks! This has been approved and merged.
