### ISSUE TITLE
encode_payload has memory leak

### ISSUE THREAD

**Issue by zyfromsh** [eclipse/tahu#70]
if execute below code 

>  size_t message_length = encode_payload(&binary_buffer, buffer_length, &ndata_payload);
the memory continue increasing

if not excute this code, the memory got stable.

does anyone know that?

**Comment by zyfromsh** [comment]
sorry, free_payload causes memeory lead not encode_payload

**Comment by jbrzozoski** [comment]
I tried to work through this issue and many others in my branch.  I haven't got around to making a pull request yet, but you can look at it on my repo if you want:
https://github.com/jbrzozoski/tahu/tree/c_client_rework

**Comment by zyfromsh** [comment]
appreciate  your efforts, I'll check this branch.
