### ISSUE TITLE
Access to tahu-java s3://cirrus-link-maven-repo/

### ISSUE THREAD

**Issue by dgradecak** [eclipse/tahu#80]
Hi,
(sorry for opening an issue for this)

is there a read only acess to you S3 maven repository? I would like to use your built artifact if that is possible 
or is this projected intended to be cloned in order to use it as a dependency?

Do you have any plan to move it to maven central or OSS instead of the private S3 bucket? 

Or the real question is, do you have any public maven repository so we can access the artifact?

**Comment by wes-johnson** [comment]
We don't have public maven repo at this point. For the short term, you must build it on your own.

**Comment by wes-johnson** [comment]
Closing as dup of #87
