### ISSUE TITLE
Misleading comment in .proto file

### ISSUE THREAD

**Issue by stankatz** [eclipse/tahu#9]
In the .proto file, the comment in line 83 for the Metrics in a Template message says "Each metric is the name of the metric and the datatype of the member but does not contain a value". This is not correct since the template message needs to provide values for the metrics both in the NBIRTH/DBIRTH message (Template definition) as well as whenever the Metric changes value in a NDATA/DDATA message.

**Comment by wes-johnson** [comment]
Fixed here: https://github.com/eclipse/tahu/pull/26/commits/33f81cd0994816fcd2aa6168ee1134d6bf3b4d96
