### ISSUE TITLE
Typo in standard

### ISSUE THREAD

**Issue by masonpawsey** [eclipse/tahu#98]
I believe there's a typo in [the standard](https://www.eclipse.org/tahu/spec/Sparkplug%20Topic%20Namespace%20and%20State%20ManagementV2.2-with%20appendix%20B%20format%20-%20Eclipse.pdf); section 9.1 references section 7.4.1, which doesn't exist. I assume this is supposed to be section 7.3.1?

**Comment by jbrzozoski** [comment]
It's definitely wrong, but I think it should actually refer to section 7.1.2 for the NBIRTH message.

**Comment by masonpawsey** [comment]
Ah, I believe you're correct, good catch!

**Comment by wes-johnson** [comment]
This spec is being rewritten as part of the Eclipse Sparkplug Working group. The Sparkplug Specification project Github repo is now here: https://github.com/eclipse/sparkplug. All new work is being done on the develop branch of that repo.
